### ISSUE TITLE
Typo under "Overview section"

### ISSUE THREAD

**Issue by mackdaniels** [learn-co-curriculum/github-pull-request-basics#13]
The concept of a pull request is unique to Github. It is a request for the owner of a receiving repository to take your changes, that you made in a parallel universe ("your fork") and "pull" them into the owner's repository. **Pull requests _are power_ the open source community.** Through this process, anyone can fork a repo, make changes and submit a pull request. Instead of the owner working on their codebase alone, anyone can contribute: tests, documentation fixes, new features, awesome layout and graphics, etc.

I think that sentence should say: Pull requests **are _the_ power of the open source community**

**Comment by sgharms** [comment]
Thanks! We've made the change.
