### ISSUE TITLE
Instructions are still not clear

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/github-pull-request-basics#14]
@sgharms 
#11 adds great information, but unfortunately does not fix the lack of clear instructions as to what is expected from the student in this lesson.

Perhaps this lesson is meant to be a readme? 

As of now, it requires a pull request to be submitted to proceed, but there are no instructions stating specifically that the student must walk through the process outlined in this lesson and submit a pull request themselves. If this is indeed the intention, perhaps replacing the theoretical example of jquery-ui with this actual repo might make it more clear as well.

**Comment by sgharms** [comment]
It is now a README.

**Comment by kwebster2** [comment]
Thanks @sgharms !
