### ISSUE TITLE
https://github.com/learn-co-students/awesome-lab returns 404

### ISSUE THREAD

**Issue by iamwhat** [learn-co-curriculum/github-pull-request-basics#15]
My understanding is that I need to fork this repo to finish the lesson.

But this repo seemed to have been deleted from Github.

![404](https://i.imgur.com/KpEUcPj.png)

**Comment by drakeltheryuujin** [comment]
Hi @iamwhat,

This lesson doesn't require an actual fork to be made. The repo only serves as an example, but doesn't actually exist. The lesson has been updated so that that is clear.

Thank you for your feedback 💙
