### ISSUE TITLE
awesome-lab URL is confusing for novices

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/github-pull-request-basics#17]
I've seen a number of students attempt to follow along with the instructions only to get confused by the fact that `https://github.com/learn-co-students/awesome-lab` is not an actual repo URL. I would suggest one of the following:

1. Clarify that this URL is only an example, and not a real URL
2. **Ideally:** Use a URL of a real, live example repo

**Comment by sgharms** [comment]
@drakeltheryuujin 

1. Can you create a repo under the org described above. 
2. Specify in the text for *this* repo that `awesome-lab` is an example
3. Add something in the awesome-lab/README.md which says "Hey, this is an example repo. If you came here, you were probably only meant to use this as an example, but good job finding it" (or something similar).

**Comment by sgharms** [comment]
@ivalentine We will work on this todayl.

**Comment by drakeltheryuujin** [comment]
@sgharms will do! I thought I had already edited a lesson like this where there was a similar issue. Maybe it was a readme and not a lab.
