### ISSUE TITLE
Instructions are unclear

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/github-pull-request-basics#19]
@sgharms 
In issue #14, this lesson was changed to a README. It appears that it is showing up as a lab requiring a pull request again. If we want to require a pull request, I think the directions need to be more clear as to what is expected from the student. As of now, the lesson reads as if we are doing a hypothetical pull request on a hypothetical repository. I think we would need give more specific instructions about each step - forking and cloning this particular repo (perhaps manually, to re-inforce past Github lessons), adding and committing changes, pushing, and finally the pull request itself.

**Comment by sgharms** [comment]
@kwebster2 Thanks for the information. The to (READ)me or not to (READ)me used to be a field in the db, but now has become something calculated. We must be tripping that calculation logic. Willfix.

**Comment by sgharms** [comment]
Should be fixed now. Thanks for the issue.
