### ISSUE TITLE
readme mentions that PRs aren't related to `git pull`

### ISSUE THREAD

**Issue by Chovin** [learn-co-curriculum/github-pull-request-basics#22]
In [README.md#explain-what-a-pull-requests-is](https://github.com/learn-co-curriculum/github-pull-request-basics/blob/5e74110007cca4f409d72b0f0c0c6e5902e992d5/README.md#explain-what-a-pull-requests-is), it mentions that `in a "pull request" this isn't really what's happening`, that it's a `git merge` instead of a `git pull`, a completely different command.

https://github.com/learn-co-curriculum/github-pull-request-basics/blob/5e74110007cca4f409d72b0f0c0c6e5902e992d5/README.md#L42-L47

This is likely incorrect and is misleading.
1. [git pull](https://www.git-scm.com/docs/git-pull) is a `git fetch` followed by a `git merge`, so `git pull` and `git merge` are completely related.
2. `in a "pull request" this isn't really what's happening.` This likely isn't true either. When you open a pull request, that is exactly what you are doing, you are requesting that the repo you're opening the PR on does a `git pull` from your fork. As the original repo does not have your fork's branches, it will need to `fetch` the branch's commits first, then `merge` them -- in other words, `git pull`.

I think this section should be removed or if clarification is wanted on the term "pull request", replaced with a few sentences clarifying why a PR is called a PR.

some sources: https://stackoverflow.com/questions/14817051/why-does-github-call-foreign-submissions-a-pull-request
https://stackoverflow.com/questions/22199432/pull-request-vs-merge-request

**Comment by drakeltheryuujin** [comment]
Thank you @Chovin,

We've updated the materials and believe that this issue has been resolved. If you don't think that the issue has been resolved, feel free to reopen an issue and we'll take another look.

Thanks for your contribution 💙

**Comment by Chovin** [comment]
The changes to this section are a good improvement, thank you! 
I don't know how github internals work but I believe it's pretty close to a `git pull`, just with some local (server-side) work trees to do the merging.

"remote" and "local" repos are only to the perspective of the cloned repo as seen below. Notice that both `git pull` and `git merge` can't be done unless something else is done as well.

```
Chovins-MBP:pr_example Chovin$ mkdir local
Chovins-MBP:pr_example Chovin$ cd local/
Chovins-MBP:local Chovin$ git init
Initialized empty Git repository in /Users/Chovin/pr_example/local/.git/
Chovins-MBP:local Chovin$ echo "1" > 1
Chovins-MBP:local Chovin$ git add 1 
Chovins-MBP:local Chovin$ git commit -m 1
[master (root-commit) 3d3dc3e] 1
 1 file changed, 1 insertion(+)
 create mode 100644 1
Chovins-MBP:local Chovin$ cd ..
Chovins-MBP:pr_example Chovin$ git clone --bare local origin
Cloning into bare repository 'origin'...
done.
Chovins-MBP:pr_example Chovin$ ls
local	origin
Chovins-MBP:pr_example Chovin$ git clone --bare origin fork
Cloning into bare repository 'fork'...
done.
Chovins-MBP:pr_example Chovin$ cd fork/
Chovins-MBP:fork Chovin$ ls
HEAD		description	info		packed-refs
config		hooks		objects		refs
Chovins-MBP:fork Chovin$ cd ..
Chovins-MBP:pr_example Chovin$ ls
fork	local	origin
Chovins-MBP:pr_example Chovin$ cd local/
Chovins-MBP:local Chovin$ git remote add fork ../fork
Chovins-MBP:local Chovin$ git remote add origin ../origin
Chovins-MBP:local Chovin$ git remote
fork
origin
Chovins-MBP:local Chovin$ touch 2
Chovins-MBP:local Chovin$ echo "2" > 2
Chovins-MBP:local Chovin$ git commit -m 2
[master 18db480] 2
 1 file changed, 1 insertion(+)
 create mode 100644 2
Chovins-MBP:local Chovin$ ls
1	2
Chovins-MBP:local Chovin$ git push fork master
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 260 bytes | 260.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../fork
   3d3dc3e..18db480  master -> master
Chovins-MBP:local Chovin$ cd ../fork/
Chovins-MBP:fork Chovin$ git log
commit 18db4802555d1518683382951c607c082dc76ea2 (HEAD -> master)
Author: Chovin <Chovin@users.noreply.github.com>
Date:   Sun Sep 30 22:50:25 2018 +1000

    2

commit 3d3dc3e019e008cfa382532e04cdefa38d67b7bc
Author: Chovin <Chovin@users.noreply.github.com>
Date:   Sun Sep 30 22:47:51 2018 +1000

    1
Chovins-MBP:fork Chovin$ cd ../origin/
Chovins-MBP:origin Chovin$ git remote
origin
Chovins-MBP:origin Chovin$ git pull ../fork master
fatal: this operation must be run in a work tree
Chovins-MBP:origin Chovin$ git fetch ../fork master
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From ../fork
 * branch            master     -> FETCH_HEAD
Chovins-MBP:origin Chovin$ git merge FETCH_HEAD 
fatal: this operation must be run in a work tree
```
