### ISSUE TITLE
Lesson not being marked as complete.

### ISSUE THREAD

**Issue by edb-c** [learn-co-curriculum/github-pull-request-basics#23]
Hi, anyway this can be corrected and marked as complete in Learn.
It is bothering my OCD.
Thank you.

**Comment by drakeltheryuujin** [comment]
Hi @edb-c! 
This request sounds like an issue with the Learn platform. [Raising issues on GitHub][raise] should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
