### ISSUE TITLE
github interface screenshots need updating

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/github-pull-request-basics#4]
The screen capture pics need updating since the github interface changed a few months ago.

**Comment by AnnJohn** [comment]
thanks @bhollan. we're aware of this and will update when we can.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
