### ISSUE TITLE
Github links don't do anything

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/github-pull-request-basics#5]
All or most of the links to Github don't work. For example, I was told to go here https://github.com/your-user-name/awesome-lab, obviously that is changed to: https://github.com/tolenno/awesome-lab. But that doesn't work.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue.

Sincerely,

Flatiron Curriculum Team
