### ISSUE TITLE
Directions for lab are unclear

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/github-pull-request-basics#8]
@cjbrock 
I don't think this lab should be in a lab format. Or, if it should be in a lab format, then I think we should add directions to instruct the student as to what is expected of them.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#10.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
