### ISSUE TITLE
It isn't at all clear what one is supposed to do in this lab

### ISSUE THREAD

**Issue by julianjohannesen** [learn-co-curriculum/github-pull-request-basics#9]
The language in this lab is unclear. After opening the IDE, it is not clear what needs to be done next. 
I was able to add some lorem ipsum, use the terminal to add, commit, and push, and then make a pull request from GitHub. That seemed to do the trick, but only used a part of the use case described in the lab.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#10.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
